routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
  ]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(["middleware" => "auth"], function() {
    Route::resource('product', 'ProductController')->except(["show"]);
    Route::resource('customer', 'CustomerController')->except(["show"]);
    Route::resource('invoice', 'InvoiceController')->except(["show"]);
    Route::delete('/invoice/{id}', 'InvoiceController@destroyInvoiceDetail')->name("invoice.destroy.detail");
    Route::get('/invoice/{id}/print', 'InvoiceController@generateInvoice')->name("invoice.print");
});

Route::any('{query}', function() { return redirect('/'); })->where('query', '.*');

app/Invoice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = ["customer_id", "total"];

    // Agar invoice atau nota dapat mengakses data customer.

    public function customer() {
        return $this->belongsTo(Customer::class);
    }

    // Agar invoice dapat mengakses data invoice detail

    public function details() {
        return $this->hasMany(Invoice_detail::class);
    }

    // Accessor
    // Akan menghasilkan sebuah filed bernama tax.
    // Diakses dengan cara $invoice->tax.

    public function getTaxAttribute() {
        return ($this->total * 2) / 100;
    }

    // Accessor.
    // Akan menghasilkan sebuah field bernama total_price.
    // Diakses dengan cara $invoice->total_price.

    public function getTotalPriceAttribute() {
        return ($this->total + (($this->total * 2) / 100));
    }
}

app/Http/Controllers/InvoiceController.php
<?php

namespace App\Http\Controllers;

use PDF;
use App\Invoice;
use App\Customer;
use App\Product;
use App\Invoice_detail;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $invoices = Invoice::with(["customer", "details"])->orderBy("created_at", "DESC")->paginate(10);

        return view("invoice.index", compact("invoices"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $customers = Customer::orderBy("created_at", "DESC")->get();

        return view("invoice.create", compact("customers"));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "customer_id" => "required|exists:customers,id"
        ]);

        $invoice = Invoice::create([
            "customer_id" => $request->customer_id,
            "total" => 0
        ]);

        return redirect(route("invoice.edit", $invoice->id));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function edit(Invoice $invoice)
    {
        // Menggunakan relationship untuk mendapatkan data customer.

        $invoice = Invoice::with(["customer", "details", "details.product"])->findOrFail($invoice->id);
        $products = Product::orderBy("created_at", "DESC")->get();

        return view("invoice.edit", compact("invoice", "products"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Invoice $invoice)
    {
        $this->validate($request, [
            "product_id" => "required|exists:products,id",
            "qty" => "required|integer"
        ]);

        $product = Product::findOrFail($request->product_id);
        $invoice_detail = $invoice->details()->where("product_id", $product->id)->first();

        if ($invoice_detail) {
            $invoice_detail->update([
                "qty" => $invoice_detail->qty + $request->qty
            ]);
        } else {
            Invoice_detail::create([
                "invoice_id" => $invoice->id,
                "product_id" => $product->id,
                "price" => $product->price,
                "qty" => $request->qty
            ]);
        }

        return redirect()->back()->with(["success" => "Produk berhasil ditambahkan."]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Invoice  $invoice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Invoice $invoice)
    {
        $invoice->delete();

        return redirect(route("invoice.index"))->with(["success" => "Invoice berhasil dihapus."]);
    }

    public function destroyInvoiceDetail($id) {
        $invoice_detail = Invoice_detail::findOrFail($id);
        $invoice_detail->delete();

        return redirect()->back()->with(["success" => "Produk berhasil dihapus."]);
    }

    public function generateInvoice($id) {
        $invoice = Invoice::with(["customer", "details", "details.product"])->findOrFail($id);

        $pdf = PDF::loadView("invoice.print", compact("invoice"))->setPaper('a4', 'landscape');

        return $pdf->stream();
    }
}

resources/views/invoice/create.blade.php
@extends('layouts.app')

@section('title')
<title>Tambah Invoice</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Invoice</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('invoice.store') }}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="customer_id">Customer</label>

                            <select name="customer_id" id="customer_id" class="form-control" required>
                                @foreach ($customers as $customer)
                                <option value="{{ $customer->id }}">{{ $customer->name }} {{ $customer->email }}
                                </option>
                                @endforeach
                            </select>
                        </div>

                        <button type="submit" class="btn btn-primary btn-sm float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/invoice/edit.blade.php
@extends('layouts.app')

@section('title')
<title>Edit Invoice</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    @if (session("success"))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session("success") }}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    <div class="row">
                        <div class="col">
                            <table>
                                <tr>
                                    <td>Pelanggan</td>
                                    <td>:</td>
                                    <td>{{ $invoice->customer->name }}</td>
                                </tr>

                                <tr>
                                    <td>Alamat</td>
                                    <td>:</td>
                                    <td>{{ $invoice->customer->address }}</td>
                                </tr>

                                <tr>
                                    <td>No Telepon</td>
                                    <td>:</td>
                                    <td>{{ $invoice->customer->phone }}</td>
                                </tr>

                                <tr>
                                    <td>Email</td>
                                    <td>:</td>
                                    <td>{{ $invoice->customer->email }}</td>
                                </tr>
                            </table>
                        </div>

                        <div class="col">
                            <table>
                                <tr>
                                    <td>Perusahaan</td>
                                    <td>:</td>
                                    <td>thenekolites</td>
                                </tr>

                                <tr>
                                    <td>Alamat</td>
                                    <td>:</td>
                                    <td>Jl. Gerilya Timur Purwokerto Selatan</td>
                                </tr>

                                <tr>
                                    <td>No Telepon</td>
                                    <td>:</td>
                                    <td>081234567890</td>
                                </tr>

                                <tr>
                                    <td>Email</td>
                                    <td>:</td>
                                    <td>support@thenekolites.com</td>
                                </tr>
                            </table>
                        </div>
                    </div>

                    {{-- Menambahkan produk untuk invoice --}}

                    <div class="row mt-5">
                        <div class="col">
                            <form action="{{ route('invoice.update', $invoice->id) }}" method="POST">
                                @csrf
                                @method("PUT")

                                <table class="table table-bordered">
                                    <tr>
                                        <td>
                                            <select name="product_id" class="form-control">
                                                @foreach ($products as $product)
                                                <option value="{{ $product->id }}">{{ $product->title }}
                                                </option>
                                                @endforeach
                                            </select>
                                        </td>

                                        <td colspan="3">
                                            <input type="number" name="qty" id="qty" min="1" value="1"
                                                class="form-control" required>
                                        </td>

                                        <td>
                                            <button type="submit" class="btn btn-primary btn-sm">Tambah</button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>

                    {{-- Daftar invoice yang ditambahkan --}}

                    <div class="row">
                        <div class="col">
                            <table class="table table-hover table-bordered">
                                <thead>
                                    <tr>
                                        <td>#</td>
                                        <td>Produk</td>
                                        <td>Qty</td>
                                        <td>Harga</td>
                                        <td>Subtotal</td>
                                        <th>Action</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @forelse ($invoice->details as $detail)
                                    <tr>
                                        <td>{{ $loop->iteration }}</td>
                                        <td>{{ $detail->product->title }}</td>
                                        <td>{{ $detail->qty }}</td>
                                        <td>Rp {{ number_format($detail->price) }}</td>
                                        <td>Rp {{ $detail->subtotal }}</td>
                                        <td>
                                            <form action="{{ route('invoice.destroy.detail', $detail->id) }}"
                                                method="POST">
                                                @csrf
                                                @method("DELETE")

                                                <button class="btn btn-danger btn-sm">Delete</button>
                                            </form>
                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td class="text-center" colspan="6">Data kosong</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-12 col-lg-4 offset-lg-8">
                            <p><b>Total Akhir</b></p>

                            <table class="table table-hover table-bordered">
                                <tr>
                                    <td>Subtotal</td>
                                    <td>:</td>
                                    <td>{{ number_format($invoice->total) }}</td>
                                </tr>

                                <tr>
                                    <td>Pajak</td>
                                    <td>:</td>
                                    <td>2% (Rp {{ number_format($invoice->tax) }})</td>
                                </tr>

                                <tr>
                                    <td>Total</td>
                                    <td>:</td>
                                    <td>Rp {{ number_format($invoice->total_price) }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/invoice/index.blade.php
@extends('layouts.app')

@section('title')
<title>Manajemen Invoice</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="card-title">Manajemen Invoice</h3>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session("success"))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session("success") }}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama Lengkap</th>
                                <th>No Telepon</th>
                                <th>Total Item</th>
                                <th>Subtotal</th>
                                <th>Pajak</th>
                                <th>Total</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($invoices as $invoice)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $invoice->customer->name }}</td>
                                <td>{{ $invoice->customer->phone }}</td>
                                <td>{{ $invoice->details->count() }}</td>
                                <td>{{ number_format($invoice->total) }}</td>
                                <td>{{ number_format($invoice->tax) }}</td>
                                <td>{{ number_format($invoice->total_price) }}</td>
                                <td>
                                    <form action="{{ route('invoice.destroy', $invoice->id) }}" method="POST">
                                        @csrf
                                        @method("DELETE")

                                        <a href="{{ route('invoice.print', $invoice->id) }}"
                                            class="btn btn-primary btn-sm">Print</a>

                                        <a href="{{ route('invoice.edit', $invoice->id) }}"
                                            class="btn btn-warning btn-sm">Edit</a>

                                        <button class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-center" colspan="8">Tidak ada data</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>

                    <div class="float-right">
                        {{ $invoices->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/invoice/print.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Invoice</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
        body {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            color: #333;
            text-align: left;
            font-size: 18px;
            margin: 0;
        }

        .container {
            margin: 0 auto;
            margin-top: 35px;
            padding: 40px;
            width: 750px;
            height: auto;
            background-color: #fff;
        }

        caption {
            font-size: 28px;
            margin-bottom: 15px;
        }

        table {
            border: 1px solid #333;
            border-collapse: collapse;
            margin: 0 auto;
            width: 740px;
        }

        td,
        tr,
        th {
            padding: 12px;
            border: 1px solid #333;
            width: 185px;
        }

        th {
            background-color: #f0f0f0;
        }

        h4,
        p {
            margin: 0px;
        }
    </style>
</head>

<body>
    <div class="container">
        <table>
            <caption>
                Thenekolites Invoice App
            </caption>

            <thead>
                <tr>
                    <th colspan="3">Invoice <strong>#{{ $invoice->id }}</strong></th>
                    <th>{{ $invoice->created_at->format('D, d M Y') }}</th>
                </tr>

                <tr>
                    <td colspan="2">
                        <h4>Perusahaan: </h4>
                        <p>Thenekolites<br>
                            Jl. Gerilya Timur Purwokerto<br>
                            081234567890<br>
                            support@thenekolites.com
                        </p>
                    </td>

                    <td colspan="2">
                        <h4>Pelanggan: </h4>
                        <p>{{ $invoice->customer->name }}<br>
                            {{ $invoice->customer->address }}<br>
                            {{ $invoice->customer->phone }} <br>
                            {{ $invoice->customer->email }}
                        </p>
                    </td>
                </tr>
            </thead>

            <tbody>
                <tr>
                    <th>Produk</th>
                    <th>Harga</th>
                    <th>Qty</th>
                    <th>Subtotal</th>
                </tr>

                @foreach ($invoice->details as $detail)
                <tr>
                    <td>{{ $detail->product->title }}</td>
                    <td>Rp {{ number_format($detail->price) }}</td>
                    <td>{{ $detail->qty }}</td>
                    <td>Rp {{ $detail->subtotal }}</td>
                </tr>
                @endforeach

                <tr>
                    <th colspan="3">Subtotal</th>
                    <td>Rp {{ number_format($invoice->total) }}</td>
                </tr>

                <tr>
                    <th>Pajak</th>
                    <td></td>
                    <td>2%</td>
                    <td>Rp {{ number_format($invoice->tax) }}</td>
                </tr>
            </tbody>

            <tfoot>
                <tr>
                    <th colspan="3">Total</th>
                    <td>Rp {{ number_format($invoice->total_price) }}</td>
                </tr>
            </tfoot>
        </table>
    </div>
</body>

</html>