routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
  ]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(["middleware" => "auth"], function() {
    Route::resource('product', 'ProductController')->except(["show"]);
    Route::resource('customer', 'CustomerController')->except(["show"]);
    Route::resource('invoice', 'InvoiceController')->except(["show"]);
    Route::delete('/invoice/{id}', 'InvoiceController@destroyInvoiceDetail')->name("invoice.destroy.detail");
    Route::get('/invoice/{id}/print', 'InvoiceController@generateInvoice')->name("invoice.print");
});

Route::any('{query}', function() { return redirect('/'); })->where('query', '.*');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::orderBy("created_at", "DESC")->get();

        return view("product.index", compact("products"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("product.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "title" => "required|string|max:100",
            "description" => "required|string",
            "price" => "required|integer",
            "stock" => "required|integer"
        ]);

        Product::create($request->except("_token"));

        return redirect(route("product.index"))->with(["success" => "Produk berhasil dibuat."]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view("product.edit", compact("product"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        $this->validate($request, [
            "title" => "required|string|max:100",
            "description" => "required|string",
            "price" => "required|integer",
            "stock" => "required|integer"
        ]);

        $product->update($request->except("_token"));

        return redirect(route("product.index"))->with(["success" => "Produk berhasil diubah."]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect(route("product.index"))->with(["success" => "Produk berhasil dihapus."]);
    }
}

resources/views/product/create.blade.php
@extends('layouts.app')

@section('title')
<title>Tambah Produk</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Produk</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('product.store') }}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="title">Nama Produk</label>
                            <input type="text" name="title" class="form-control" id="title"
                                placeholder="Masukkan nama produk">

                            <p class="text-danger">{{ $errors->first('title') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="description">Deskripsi Produk</label>
                            <textarea name="description" class="form-control" id="description" rows="3"
                                placeholder="Masukkan deskripsi produk"></textarea>

                            <p class="text-danger">{{ $errors->first('description') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="price">Harga Produk</label>
                            <input type="number" name="price" class="form-control" id="price"
                                placeholder="Masukkan harga produk" value="0">

                            <p class="text-danger">{{ $errors->first('price') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="stock">Stok Produk</label>
                            <input type="number" name="stock" class="form-control" id="stock"
                                placeholder="Masukkan stok produk" value="0">

                            <p class="text-danger">{{ $errors->first('stock') }}</p>
                        </div>

                        <button type="submit" class="btn btn-primary btn-sm float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.app')

@section('title')
<title>Edit Produk</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Produk</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('product.update', $product->id) }}" method="POST">
                        @csrf
                        @method("PUT")

                        <div class="form-group">
                            <label for="title">Nama Produk</label>
                            <input type="text" name="title" class="form-control" id="title"
                                placeholder="Masukkan nama produk" value="{{ $product->title }}">

                            <p class="text-danger">{{ $errors->first('title') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="description">Deskripsi Produk</label>
                            <textarea name="description" class="form-control" id="description" rows="3"
                                placeholder="Masukkan deskripsi produk"
                                value="{{ $product->description }}">{{ $product->description }}</textarea>

                            <p class="text-danger">{{ $errors->first('description') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="price">Harga Produk</label>
                            <input type="number" name="price" class="form-control" id="price"
                                placeholder="Masukkan harga produk" value="{{ $product->price }}">

                            <p class="text-danger">{{ $errors->first('price') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="stock">Stok Produk</label>
                            <input type="number" name="stock" class="form-control" id="stock"
                                placeholder="Masukkan stok produk" value="{{ $product->stock }}">

                            <p class="text-danger">{{ $errors->first('stock') }}</p>
                        </div>

                        <button type="submit" class="btn btn-primary btn-sm float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.app')

@section('title')
<title>Manajemen Produk</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="card-title">Manajemen Produk</h3>
                        </div>

                        <div class="col">
                            <a href="{{ route('product.create') }}" class="btn btn-primary btn-sm float-right">Tambah
                                Produk</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session("success"))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session("success") }}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama Produk</th>
                                <th>Deskripsi</th>
                                <th>Harga</th>
                                <th>Stok</th>
                                <th>Tanggal</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($products as $product)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $product->title }}</td>
                                <td>{{ $product->description }}</td>
                                <td>{{ $product->price }}</td>
                                <td>{{ $product->stock }}</td>
                                <td>{{ $product->created_at->format("d-m-Y") }}</td>
                                <td>
                                    <form action="{{ route('product.destroy', $product->id) }}" method="POST">
                                        @csrf
                                        @method("DELETE")

                                        <a href="{{ route('product.edit', $product->id) }}"
                                            class="btn btn-warning btn-sm">Edit</a>

                                        <button class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-center" colspan="7">Tidak ada data</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection