routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
  ]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(["middleware" => "auth"], function() {
    Route::resource('product', 'ProductController')->except(["show"]);
    Route::resource('customer', 'CustomerController')->except(["show"]);
    Route::resource('invoice', 'InvoiceController')->except(["show"]);
    Route::delete('/invoice/{id}', 'InvoiceController@destroyInvoiceDetail')->name("invoice.destroy.detail");
    Route::get('/invoice/{id}/print', 'InvoiceController@generateInvoice')->name("invoice.print");
});

Route::any('{query}', function() { return redirect('/'); })->where('query', '.*');

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $guarded = [];
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use Illuminate\Http\Request;

class CustomerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $customers = Customer::orderBy("created_at", "DESC")->paginate(10);

        return view("customer.index", compact("customers"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("customer.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required|string",
            "phone" => "required|max:13",
            "address" => "required|string",
            "email" => "required|email|string|unique:customers,email"
        ]);

        Customer::create($request->except("_token"));

        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil ditambahkan."]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Customer $customer)
    {
        return view("customer.edit", compact("customer"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer)
    {
        $this->validate($request, [
            "name" => "required|string",
            "phone" => "required|max:13",
            "address" => "required|string",
            "email" => "required|email|string|unique:customers,email," . $customer->id
        ]);

        $customer->update($request->except("_token"));

        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil diubah."]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Customer $customer)
    {
        $customer->delete();

        return redirect(route("customer.index"))->with(["success" => "Pelanggan berhasil dihapus."]);
    }
}

resources/views/customer/create.blade.php
@extends('layouts.app')

@section('title')
<title>Tambah Pelanggan</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Tambah Pelanggan</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('customer.store') }}" method="POST">
                        @csrf

                        <div class="form-group">
                            <label for="name">Nama Pelanggan</label>
                            <input type="text" name="name" class="form-control" id="name"
                                placeholder="Masukkan nama pelanggan" value="{{ old('name') }}">

                            <p class="text-danger">{{ $errors->first('name') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="email">Email Pelanggan</label>
                            <input type="email" name="email" class="form-control" id="email"
                                placeholder="Masukkan email pelanggan" value="{{ old('email') }}">

                            <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="phone">No Telepon</label>
                            <input type="number" name="phone" class="form-control" id="phone"
                                placeholder="Masukkan nomor telepon pelanggan" value="{{ old('phone') }}">

                            <p class="text-danger">{{ $errors->first('phone') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="address">Alamat Pelanggan</label>
                            <textarea name="address" class="form-control" id="address" rows="3"
                                placeholder="Masukkan alamat pelanggan"
                                value="{{ old('address') }}">{{ old('address') }}</textarea>

                            <p class="text-danger">{{ $errors->first('address') }}</p>
                        </div>

                        <button type="submit" class="btn btn-primary btn-sm float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/edit.blade.php
@extends('layouts.app')

@section('title')
<title>Edit Pelanggan</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Edit Pelanggan</h3>
                </div>

                <div class="card-body">
                    <form action="{{ route('customer.update', $customer->id) }}" method="POST">
                        @csrf
                        @method("PUT")

                        <div class="form-group">
                            <label for="name">Nama Pelanggan</label>
                            <input type="text" name="name" class="form-control" id="name"
                                placeholder="Masukkan nama pelanggan" value="{{ $customer->name }}">

                            <p class="text-danger">{{ $errors->first('name') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="email">Email Pelanggan</label>
                            <input type="email" name="email" class="form-control" id="email"
                                placeholder="Masukkan email pelanggan" value="{{ $customer->email }}">

                            <p class="text-danger">{{ $errors->first('email') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="phone">No Telepon</label>
                            <input type="number" name="phone" class="form-control" id="phone"
                                placeholder="Masukkan nomor telepon pelanggan" value="{{ $customer->phone }}">

                            <p class="text-danger">{{ $errors->first('phone') }}</p>
                        </div>

                        <div class="form-group">
                            <label for="address">Alamat Pelanggan</label>
                            <textarea name="address" class="form-control" id="address" rows="3"
                                placeholder="Masukkan alamat pelanggan"
                                value="{{ $customer->address }}">{{ $customer->address }}</textarea>

                            <p class="text-danger">{{ $errors->first('address') }}</p>
                        </div>

                        <button type="submit" class="btn btn-primary btn-sm float-right">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/customer/index.blade.php
@extends('layouts.app')

@section('title')
<title>Manajemen Pelanggan</title>
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col">
                            <h3 class="card-title">Manajemen Pelanggan</h3>
                        </div>

                        <div class="col">
                            <a href="{{ route('customer.create') }}" class="btn btn-primary btn-sm float-right">Tambah
                                Pelanggan</a>
                        </div>
                    </div>
                </div>

                <div class="card-body">
                    @if (session("success"))
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        {{ session("success") }}

                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    @endif

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Nama Pelanggan</th>
                                <th>No Telepon</th>
                                <th>Alamat</th>
                                <th>Email</th>
                                <th colspan="2" class="text-center">Aksi</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($customers as $customer)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $customer->name }}</td>
                                <td>{{ $customer->phone }}</td>
                                <td>{{ $customer->address }}</td>
                                <td>{{ $customer->email }}</td>
                                <td>
                                    <form action="{{ route('customer.destroy', $customer->id) }}" method="POST">
                                        @csrf
                                        @method("DELETE")

                                        <a href="{{ route('customer.edit', $customer->id) }}"
                                            class="btn btn-warning btn-sm">Edit</a>

                                        <button class="btn btn-danger btn-sm">Hapus</button>
                                    </form>
                                </td>

                                <td>
                                    <form action="{{ route('invoice.store') }}" method="POST">
                                        @csrf

                                        <input type="hidden" name="customer_id" value="{{ $customer->id }}"
                                            class="form-control">
                                        <button class="btn btn-primary btn-sm">Buat Invoice</button>
                                    </form>
                                </td>
                            </tr>
                            @empty
                            <tr>
                                <td class="text-center" colspan="6">Tidak ada data</td>
                            </tr>
                            @endforelse
                        </tbody>
                    </table>

                    <div class="float-right">
                        {{ $customers->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection